### PR TITLE
Update Hooks to Cucumber V3

### LINKED ISSUE #35: Sauce service produces type errors trying to read cucumber feature params
Since updating to a newer version of cucumber, we are seeing type errors as the function names and params have changed.  These need to be updated otherwise:

```
16:35:42     at execHook (/home/jenkins/workspace/QUARTS-Regression-Suite/node_modules/wdio-sync/build/index.js:166:35)
16:35:43 ․TypeError: feature.getFailureException is not a function
16:35:43     at SauceService.afterStep (/home/jenkins/workspace/QUARTS-Regression-Suite/node_modules/wdio-sauce-service/build/sauce-service.js:94:25)
16:35:43     at execHook (/home/jenkins/workspace/QUARTS-Regression-Suite/node_modules/wdio-sync/build/index.js:166:35)
16:35:44 ․TypeError: feature.getFailureException is not a function
16:35:44     at SauceService.afterStep (/home/jenkins/workspace/QUARTS-Regression-Suite/node_modules/wdio-sauce-service/build/sauce-service.js:94:25)
16:35:44     at execHook (/home/jenkins/workspace/QUARTS-Regression-Suite/node_modules/wdio-sync/build/index.js:166:35)
16:35:46 ․TypeError: feature.getName is not a function
16:35:46     at SauceService.beforeFeature (/home/jenkins/workspace/QUARTS-Regression-Suite/node_modules/wdio-sauce-service/build/sauce-service.js:88:39)
16:35:46     at execHook (/home/jenkins/workspace/QUARTS-Regression-Suite/node_modules/wdio-sync/build/index.js:166:35)
16:35:46 TypeError: scenario.getName is not a function
16:35:46     at SauceService.beforeScenario (/home/jenkins/workspace/QUARTS-Regression-Suite/node_modules/wdio-sauce-service/build/sauce-service.js:105:74)
16:35:46     at execHook (/home/jenkins/workspace/QUARTS-Regression-Suite/node_modules/wdio-sync/build/index.js:166:35)
```

This also results in tests not being tagged properly, so the sauce on-demand reporter for Jenkins shows everything passing as a false-positive, even though the xunit reporter and other reporters will show otherwise.

### PR DESCRIPTION
**Pull request by BenoitAverty**
Close #35

This is a follow-up to PR #36 since @dcypherthis does not seem to have time to finish. I have taken his commit and added a change for backward compatibility.

I am currently in the train with a very limited connectivity so I have not been able to test his yet, but the change is pretty trivial and I had previously tested the change of PR #36 (it worked fine)

If you don't fell confident about the change, feel free to wait until next week, I should be able to do a quick test.

Thanks again to @dcypherthis for the initial diagnosis of the problem and implementation.

### CODE REVIEW

**Review by christian-bromann — CHANGES_REQUESTED** [review]
can you please add a comment in the readme somewhere saying that with the next version you need at least version x of the wdio-cucumber-framework.
Or even better can we make the change in a way that it is backwards compatible?

**Comment by BenoitAverty** [comment]
The change should be backwards compatible, this is the difference with #36.

**Review by christian-bromann — APPROVED** [review]
Right, make sense. All good then!

**Comment by BenoitAverty** [comment]
Hello @christian-bromann, do you know when this might be released ? Thanks in advance !

**Comment by adenflorian** [comment]
@christian-bromann Will this be published to npm soon? Thanks.

**Comment by christian-bromann** [comment]
@BenoitAverty @AdenFlorian just published `v0.4.1` sorry for the delay

**Pull request merged**
